### ISSUE TITLE
[ "useCaveFog": true ] makes the sun and moon disappear when shaders is enabled.

### ISSUE THREAD

**Issue by mateus3c** [shizotoaster/foglooksmodernnow#3]
for some reason the vanilla sun and moon dissapear when useCaveFog is set to true while playing with shaders. If set to false both vanilla sun and moon reappear normally to the sky with shaders enabled.

**Comment by shizotoaster** [comment]
Are you running on Optifine or on Oculus? Does this happen with every shader or with some certain ones?

**Comment by shizotoaster** [comment]
Confirmed. Happens with Fabric counterpart as well so I guess that's a bug from the original Forge mod

**Comment by mateus3c** [comment]
It happens with every shaders, I was running with oculus.
Is this a fixable bug?

**Comment by shizotoaster** [comment]
Probably fixable but I'm not sure what causing it. Will try to find a solution ASAP

**Comment by mateus3c** [comment]
wow, thank you very much!

**Comment by shizotoaster** [comment]
Fixed in 1.2.0

**Comment by mateus3c** [comment]
weird, I just tested and the issue persists on forge 1.20.1, any idea what might have happened?

**Comment by shizotoaster** [comment]
Please make sure you are using version 1.2.0 and latest Oculus. Does the bug still occur with only Oculus and FLMN installed?

**Comment by mateus3c** [comment]
Yes im on latest version of both FLMN and Oculus, the issue only happens if Cave Fog is enabled, if I disable it everything goes back to normal

**Comment by shizotoaster** [comment]
Figured it out. Oculus 1.6.9 had two `modid`s: `iris` and `oculus`. `iris` modid was removed in Oculus 1.6.13 so only `oculus` left. The fix only works if mod with `iris` modid is loaded - that's why it stopped working. I'll post a hotfix soon

**Comment by mateus3c** [comment]
great! thank you very much!
